name: Build and Tests

on: [push]

jobs:
  dotnetcore:
    runs-on: ubuntu-latest
    env:
      working-directory: ./src/PotterKata

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.100'
    - name: Build
      run: dotnet build --configuration Release
      working-directory: ${{env.working-directory}}
    - name: Unit Tests
      run: dotnet test
      working-directory: ${{env.working-directory}}
